import { Product } from './types';

export const BRANDS = [
  { id: 'b-leica', name: 'Leica Geosystems', slug: 'leica', country: 'Thụy Sĩ', officialDealer: true },
  { id: 'b-trimble', name: 'Trimble Navigation', slug: 'trimble', country: 'Mỹ', officialDealer: true },
  { id: 'b-topcon', name: 'Topcon Positioning', slug: 'topcon', country: 'Nhật Bản', officialDealer: true },
  { id: 'b-sokkia', name: 'Sokkia Corporation', slug: 'sokkia', country: 'Nhật Bản', officialDealer: true },
  { id: 'b-chcnav', name: 'CHCNAV (Huace)', slug: 'chcnav', country: 'Trung Quốc', officialDealer: true },
  { id: 'b-south', name: 'South Surveying', slug: 'south', country: 'Trung Quốc', officialDealer: true },
  { id: 'b-foif', name: 'FOIF Suzhou', slug: 'foif', country: 'Trung Quốc', officialDealer: true },
  { id: 'b-nikon', name: 'Nikon Trimble', slug: 'nikon', country: 'Nhật Bản', officialDealer: true },
];

export const CATEGORIES = [
  {
    id: 'c-rtk',
    name: 'Máy Định Vị GNSS RTK',
    slug: 'may-dinh-vi-gnss-rtk',
    description: 'Hệ thống định vị vệ tinh độ chính xác centimet, bù nghiêng IMU, thu nhận đa vệ tinh GPS, BDS, Galileo, GLONASS.',
    icon: 'Satellite',
  },
  {
    id: 'c-total-station',
    name: 'Máy Toàn Đạc Điện Tử',
    slug: 'may-toan-dac-dien-tu',
    description: 'Đo góc độ chính xác 1" - 2", EDM không gương cự ly xa tới 1000m - 2000m phục vụ thi công cầu đường, nhà cao tầng.',
    icon: 'Crosshair',
  },
  {
    id: 'c-optical-level',
    name: 'Máy Thủy Bình Tự Động',
    slug: 'may-thuy-binh-tu-dong',
    description: 'Thiết bị đo cao độ chuẩn xác, con lắc từ tính tự cân bằng, đo quan trắc lún và san lấp mặt bằng.',
    icon: 'Layers',
  },
  {
    id: 'c-theodolite',
    name: 'Máy Kinh Vĩ Điện Tử',
    slug: 'may-kinh-vi-dien-tu',
    description: 'Thiết bị đo góc bằng và góc đứng chuyên dụng cho trắc địa xây dựng công trình dân dụng.',
    icon: 'Compass',
  },
  {
    id: 'c-accessories',
    name: 'Phụ Kiện Trắc Địa Cao Cấp',
    slug: 'phu-kien-trac-dia',
    description: 'Gương đơn, gương mini, sào gương carbon, chân máy nặng hợp kim nhôm, pin sạc chính hãng và cáp truyền dữ liệu.',
    icon: 'Wrench',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-leica-gs18t',
    slug: 'may-dinh-vi-gnss-rtk-leica-gs18-t',
    sku: 'RTK-LEICA-GS18T',
    name: 'Máy Định Vị GNSS RTK Leica GS18 T (Bù Nghiêng IMU)',
    brand: BRANDS[0],
    category: CATEGORIES[0],
    basePrice: 285000000,
    stock: 4,
    condition: 'NEW_100',
    origin: 'Thụy Sĩ',
    warrantyMonths: 36,
    isQuoteOnly: true,
    isFeatured: true,
    rating: 5.0,
    reviewCount: 18,
    mainImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: 'Đỉnh cao RTK GNSS thế giới với công nghệ bù nghiêng IMU không cần cân bằng bọt thủy, miễn nhiễm 100% với từ trường kim loại.',
    fullDesc: 'Leica GS18 T là đầu thu GNSS RTK nhanh nhất và dễ sử dụng nhất thế giới hiện nay. Nhờ công nghệ cảm biến quán tính IMU tiên tiến, kỹ sư trắc địa không còn phải nhìn bọt thủy hay giữ thẳng sào gương khi đo. Bạn có thể đo điểm góc tường, gốc cây, mép hố ga ngập nước hay chân taluy mà vẫn giữ nguyên độ chính xác milimet. Thiết bị hoàn toàn miễn nhiễm với ảnh hưởng từ tính của cốt thép, xe cộ hay trạm biến áp cao thế.',
    highlights: [
      '555 kênh đa tần số, bắt trọn vẹn GPS, GLONASS, Galileo, BeiDou, QZSS',
      'Bù nghiêng IMU độc quyền Leica không cần hiệu chuẩn tại hiện trường',
      'Độ chính xác RTK: Ngang 8mm + 1ppm / Đứng 15mm + 1ppm RMS',
      'Tiêu chuẩn bảo vệ IP68 (ngâm nước 1.4m trong 2 giờ, rơi từ 2m xuống bê tông)',
      'Hỗ trợ công nghệ Leica SmartLink khắc phục mất tín hiệu RTK liên tục 10 phút',
    ],
    standardPackage: [
      '01 Đầu thu GNSS Leica GS18 T',
      '02 Pin sạc thông minh Leica GEB331',
      '01 Bộ sạc đôi Leica GKL341 Quick Charger',
      '01 Sào gương Carbon Leica GLS13 ren 5/8"',
      '01 Sổ tay điều khiển Leica CS20 4G LTE',
      '01 Thùng máy chống sốc tiêu chuẩn quân đội',
      'Giấy kiểm định hiệu chuẩn Vilas / Quatest 1',
    ],
    specs: {
      categoryType: 'GNSS_RTK',
      channels: 555,
      constellations: 'GPS (L1, L2, L2C, L5), GLONASS, Galileo, BeiDou (B1, B2, B3), QZSS, NavIC',
      horizontalAccuracy: '8 mm + 1 ppm RMS',
      verticalAccuracy: '15 mm + 1 ppm RMS',
      tiltCompensation: 'Cảm biến IMU 60°, bù sai lệch tự động, chống nhiễu từ trường 100%',
      uhfPower: '1W / 4W Radio trong tích hợp',
      batteryLifeHours: 12,
      weightKg: 1.2,
      ingressProtection: 'IP68 / MIL-STD-810G',
      extraDetails: {
        'Tốc độ cập nhật': '20 Hz tiêu chuẩn',
        'Bộ nhớ trong': 'Bộ nhớ 4GB thẻ MicroSD mở rộng',
        'Môi trường hoạt động': '-40°C đến +65°C',
      },
    },
    variants: [
      { id: 'v1', sku: 'RTK-LEICA-GS18T-ROVER', name: 'Bộ Rover Đơn (Kèm sổ CS20)', priceAdjustment: 0, stock: 3 },
      { id: 'v2', sku: 'RTK-LEICA-GS18T-BASE-ROVER', name: 'Trọn Bộ Base + Rover + Radio 35W', priceAdjustment: 190000000, stock: 1 },
    ],
    downloads: [
      { id: 'd1', title: 'Brochure Thông Số Kỹ Thuật Leica GS18 T (PDF)', docType: 'CATALOG_PDF', fileUrl: '#', fileSize: '4.2 MB' },
      { id: 'd2', title: 'Mẫu Giấy Chứng Nhận Kiểm Định Hiệu Chuẩn Quatest', docType: 'CALIBRATION_CERT', fileUrl: '#', fileSize: '1.8 MB' },
      { id: 'd3', title: 'Sổ Tay Hướng Dẫn Đo RTK & Phần Mềm Leica Captivate', docType: 'USER_MANUAL', fileUrl: '#', fileSize: '8.5 MB' },
    ],
  },
  {
    id: 'prod-chcnav-i73p',
    slug: 'may-dinh-vi-gnss-rtk-chcnav-i73-plus',
    sku: 'RTK-CHCNAV-I73P',
    name: 'Máy Định Vị GNSS RTK CHCNAV i73+ (1408 Kênh - IMU 60°)',
    brand: BRANDS[4],
    category: CATEGORIES[0],
    basePrice: 75000000,
    salePrice: 68000000,
    stock: 15,
    condition: 'NEW_100',
    origin: 'Trung Quốc',
    warrantyMonths: 24,
    isQuoteOnly: false,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 42,
    mainImage: 'https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: 'Pocket GNSS RTK nhỏ gọn nhất phân khúc chỉ 0.73kg, trang bị 1408 kênh siêu nhạy, thuật toán iStar bắt trọn 60+ vệ tinh liên tục.',
    fullDesc: 'CHCNAV i73+ là dòng máy định vị vệ tinh RTK bán chạy số 1 tại thị trường Việt Nam trong phân khúc tầm trung. Sở hữu 1408 kênh kết hợp thuật toán độc quyền iStar, máy bắt được tất cả các tín hiệu vệ tinh hiện có (GPS, GLONASS, Galileo, BeiDou thế hệ 3). Cảm biến bù nghiêng IMU 60 độ giúp kỹ sư đo điểm khuất mà không cần căn chỉnh bọt thủy, nâng cao hiệu suất đo đạc lên tới 30%.',
    highlights: [
      '1408 kênh thế hệ mới, hỗ trợ toàn bộ chòm vệ tinh BDS-3, GPS, GLONASS, Galileo',
      'Bù nghiêng IMU 60° tự động khởi tạo cực nhanh chỉ trong 5 giây',
      'Trọng lượng siêu nhẹ chỉ 730g cả pin, giảm tối đa mỏi tay khi đi đo cả ngày',
      'Pin dung lượng cao cho thời gian đo liên tục tới 15 giờ ở chế độ Rover 4G/CORS',
      'Tích hợp modem 4G toàn dải và Radio UHF 2W thu phát linh hoạt',
    ],
    standardPackage: [
      '01 Đầu thu CHCNAV i73+ Pocket GNSS',
      '01 Sổ tay điều khiển chuyên dụng HCE600 Android (Màn hình siêu sáng chống lóa)',
      '01 Phần mềm khảo sát LandStar 8 bản quyền trọn đời',
      '01 Gá kẹp sổ tay + Ăng-ten Radio UHF',
      '01 Sào đo carbon 2.2m CHCNAV',
      '01 Hộp sạc nhanh Type-C + Cáp truyền',
      '01 Hộp nhựa chống sốc cao cấp',
    ],
    specs: {
      categoryType: 'GNSS_RTK',
      channels: 1408,
      constellations: 'GPS, GLONASS, BeiDou (B1I, B2I, B3I, B1C, B2a, B2b), Galileo, QZSS, SBAS',
      horizontalAccuracy: '8 mm + 1 ppm RMS',
      verticalAccuracy: '15 mm + 1 ppm RMS',
      tiltCompensation: 'Cảm biến IMU 60° sai số đo góc < 2.5cm',
      uhfPower: 'Radio trong 2W phát xa 5-8km',
      batteryLifeHours: 15,
      weightKg: 0.73,
      ingressProtection: 'IP67 / Chống rơi 2m',
      extraDetails: {
        'Kết nối không dây': 'Bluetooth 5.0, Wi-Fi, NFC 1-chạm',
        'Bộ nhớ trong': '8GB eMMC lưu dữ liệu đo tĩnh',
        'Cổng sạc': 'USB Type-C hỗ trợ sạc dự phòng',
      },
    },
    variants: [
      { id: 'v-chc-1', sku: 'RTK-CHCNAV-I73P-ROVER', name: 'Bộ Rover i73+ Kèm Sổ HCE600', priceAdjustment: 0, stock: 12 },
      { id: 'v-chc-2', sku: 'RTK-CHCNAV-I73P-COMBO', name: 'Combo Trạm Base i73+ & Rover i73+ & Radio 35W', priceAdjustment: 62000000, stock: 3 },
    ],
    downloads: [
      { id: 'd-chc-1', title: 'Tài Liệu Kỹ Thuật CHCNAV i73+ (PDF)', docType: 'CATALOG_PDF', fileUrl: '#', fileSize: '3.1 MB' },
      { id: 'd-chc-2', title: 'Hướng Dẫn Cài Đặt Trạm CORS Cục Đo Đạc Bản Đồ', docType: 'USER_MANUAL', fileUrl: '#', fileSize: '2.4 MB' },
    ],
  },
  {
    id: 'prod-south-galaxy-g1',
    slug: 'may-dinh-vi-gnss-rtk-south-galaxy-g1-plus',
    sku: 'RTK-SOUTH-G1PLUS',
    name: 'Máy Định Vị GNSS RTK South Galaxy G1 Plus (1598 Kênh - Radio 4W)',
    brand: BRANDS[5],
    category: CATEGORIES[0],
    basePrice: 65000000,
    salePrice: 59000000,
    stock: 8,
    condition: 'NEW_100',
    origin: 'Trung Quốc',
    warrantyMonths: 24,
    isQuoteOnly: false,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 29,
    mainImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: '1598 kênh mainboard SoC thế hệ mới, tích hợp radio phát cực mạnh 4W truyền xa tới 15km không cần radio ngoài.',
    fullDesc: 'South Galaxy G1 Plus nâng cấp toàn diện với bo mạch 1598 kênh siêu mạnh mẽ. Công suất Radio UHF phát trong lên tới 4W cho phép đo đạc ở các vùng núi hiểm trở hoặc hải đảo xa xôi nơi không có sóng điện thoại 4G. Hệ thống pin kép tháo rời hỗ trợ thay pin nóng không cần tắt máy.',
    highlights: [
      '1598 kênh xử lý song song tín hiệu đa vệ tinh',
      'Radio trong công suất 4W phát xa vượt trội so với các đối thủ cùng tầm giá',
      'Bù nghiêng IMU 60° không lo ảnh hưởng từ trường',
      '2 pin rời dung lượng lớn, thay pin nóng trong khi máy vẫn đang hoạt động',
    ],
    standardPackage: [
      '01 Đầu thu South Galaxy G1 Plus',
      '02 Quả pin dung lượng cao 3400mAh',
      '01 Đốc sạc đôi thông minh',
      '01 Sổ tay H6 thế hệ mới bàn phím số',
      '01 Sào carbon South 2.45m',
      '01 Vali đựng chống va đập tiêu chuẩn',
    ],
    specs: {
      categoryType: 'GNSS_RTK',
      channels: 1598,
      constellations: 'GPS, GLONASS, BeiDou BDS-3, Galileo, QZSS, SBAS',
      horizontalAccuracy: '8 mm + 1 ppm RMS',
      verticalAccuracy: '15 mm + 1 ppm RMS',
      tiltCompensation: 'IMU 60 độ tự động cân bằng',
      uhfPower: 'Radio trong 1W / 2W / 4W dải tần 410-470MHz',
      batteryLifeHours: 16,
      weightKg: 0.95,
      ingressProtection: 'IP68',
    },
  },
  {
    id: 'prod-leica-ts07',
    slug: 'may-toan-dac-dien-tu-leica-flexline-ts07',
    sku: 'TS-LEICA-TS07',
    name: 'Máy Toàn Đạc Điện Tử Leica FlexLine TS07 (Độ Chính Xác 1" / 2")',
    brand: BRANDS[0],
    category: CATEGORIES[1],
    basePrice: 195000000,
    stock: 3,
    condition: 'NEW_100',
    origin: 'Thụy Sĩ',
    warrantyMonths: 24,
    isQuoteOnly: true,
    isFeatured: true,
    rating: 5.0,
    reviewCount: 14,
    mainImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: 'Dòng máy toàn đạc cao cấp Thụy Sĩ tích hợp công nghệ tự động đo chiều cao máy AutoHeight đầu tiên trên thế giới.',
    fullDesc: 'Leica FlexLine TS07 được trang bị phần mềm hiện trường trực quan Leica FlexField và tính năng tự động đo chiều cao AutoHeight mang tính cách mạng. Tính năng này giúp loại bỏ hoàn toàn các sai số thủ công khi đo thước dây và tiết kiệm đáng kể thời gian thiết lập trạm máy.',
    highlights: [
      'Tùy chọn độ chính xác góc 1" hoặc 2" tiêu chuẩn công trình ngầm và cầu đường',
      'Đo không gương PinPoint EDM cực xa: 1000m (tùy chọn mở rộng 2000m)',
      'Công nghệ AutoHeight: Tự động đo chiều cao máy bằng tia laser chỉ 1 nút bấm',
      'Màn hình cảm ứng màu 3.5" kết hợp bàn phím số đầy đủ có đèn chiếu sáng',
      'Hệ thống bù trục 4 phương quadrupled axis tự động bù sai số cân bằng',
    ],
    standardPackage: [
      '01 Thân máy toàn đạc Leica FlexLine TS07',
      '01 Đế rọi tâm laser Leica GDF311',
      '02 Pin Li-Ion Leica GEB361',
      '01 Bộ nạp pin Leica GKL311',
      '01 Cáp truyền số liệu Leica USB GEV223',
      '01 Khăn lau quang học + Túi che mưa',
      '01 Thùng máy chống sốc kèm dây đeo',
    ],
    specs: {
      categoryType: 'TOTAL_STATION',
      angularAccuracy: '1" / 2" (Tùy phiên bản đặt hàng)',
      reflectorlessRange: '1000 m (Mở rộng 2000 m)',
      prismRange: '3500 m (Gương đơn GPR1)',
      edmSpeed: '0.3 giây chế độ đo nhanh',
      batteryLifeHours: 18,
      weightKg: 4.4,
      ingressProtection: 'IP66',
      extraDetails: {
        'Độ phóng đại': '30x',
        'Bộ nhớ': '2GB Flash / Hỗ trợ thẻ USB Flash',
        'Màn hình': '3.5 inch Color QVGA Touchscreen',
      },
    },
    downloads: [
      { id: 'd-ts-1', title: 'Catalog Chi Tiết Leica TS07 FlexLine (PDF)', docType: 'CATALOG_PDF', fileUrl: '#', fileSize: '5.8 MB' },
      { id: 'd-ts-2', title: 'Chứng Nhận Hiệu Chuẩn Phòng Thí Nghiệm Đo Lường', docType: 'CALIBRATION_CERT', fileUrl: '#', fileSize: '1.2 MB' },
    ],
  },
  {
    id: 'prod-topcon-gm52',
    slug: 'may-toan-dac-dien-tu-topcon-gm-52',
    sku: 'TS-TOPCON-GM52',
    name: 'Máy Toàn Đạc Điện Tử Topcon GM-52 (Chính Hãng Nhật Bản)',
    brand: BRANDS[2],
    category: CATEGORIES[1],
    basePrice: 125000000,
    stock: 6,
    condition: 'NEW_100',
    origin: 'Nhật Bản',
    warrantyMonths: 24,
    isQuoteOnly: false,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 22,
    mainImage: 'https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: 'Độ chính xác góc 2", đo không gương 500m tốc độ siêu nhanh 0.9s, xuất xứ Nhật Bản siêu bền bỉ.',
    fullDesc: 'Topcon GM-52 đại diện cho chất lượng quang học và độ bền cơ khí đỉnh cao của Nhật Bản. Thân máy đạt chuẩn chống nước bụi IP66, chịu được mưa rào nặng hạt và bụi mịn công trường mà không bị ẩm mốc lăng kính. Khả năng đo không gương 500m giúp kỹ sư dễ dàng kiểm tra các điểm cao nguy hiểm.',
    highlights: [
      'Độ chính xác đo góc 2" theo tiêu chuẩn ISO 17123-3',
      'Đo không gương 500m cự ly xa với tia laser hội tụ siêu nhỏ',
      'Thời lượng pin vượt trội lên tới 14 giờ đo liên tục cả góc và khoảng cách',
      'Bảo hành 24 tháng chính hãng tại trung tâm bảo hành ủy quyền Topcon',
    ],
    standardPackage: [
      '01 Thân máy Topcon GM-52',
      '01 Pin sạc BDC46C',
      '01 Bộ sạc pin CDC68A',
      '01 Chân máy nhôm chính hãng Topcon',
      '01 Gương đơn + Sào gương 2.15m',
      '01 Hộp đựng máy và sách hướng dẫn sử dụng tiếng Việt',
    ],
    specs: {
      categoryType: 'TOTAL_STATION',
      angularAccuracy: '2"',
      reflectorlessRange: '500 m',
      prismRange: '4000 m (Gương đơn)',
      edmSpeed: '0.9s không gương / 0.3s có gương',
      batteryLifeHours: 14,
      weightKg: 5.1,
      ingressProtection: 'IP66',
    },
  },
  {
    id: 'prod-leica-na730',
    slug: 'may-thuy-binh-tu-dong-leica-na730-plus',
    sku: 'LV-LEICA-NA730P',
    name: 'Máy Thủy Bình Tự Động Leica NA730 Plus (30x - 0.7mm/km)',
    brand: BRANDS[0],
    category: CATEGORIES[2],
    basePrice: 9800000,
    stock: 20,
    condition: 'NEW_100',
    origin: 'Thụy Sĩ',
    warrantyMonths: 36,
    isQuoteOnly: false,
    isFeatured: true,
    rating: 5.0,
    reviewCount: 35,
    mainImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: 'Độ phóng đại 30x, độ chính xác đo đi đo về 1km đạt 0.7mm, ống kính bơm khí Nitơ chống đọng sương chuẩn quân đội.',
    fullDesc: 'Leica NA730 Plus là dòng máy thủy bình tự động hàng đầu thế giới được các viện khảo sát và tổng công ty xây dựng tin dùng cho các dự án thủy điện, hầm chui, cao ốc đòi hỏi độ chính xác cao độ tuyệt đối. Ống kính được nạp khí Nitơ giúp ngăn chặn hoàn toàn hiện tượng mờ sương khi thay đổi nhiệt độ đột ngột.',
    highlights: [
      'Độ chính xác đo cao: 0.7mm / 1km đo lặp đi lặp lại',
      'Độ phóng đại lăng kính 30x cho tầm nhìn xa rõ nét',
      'Bơm khí Nitơ bên trong thân máy chống ẩm mốc quang học trọn đời',
      'Bảo hành chính hãng 3 năm (36 tháng) — duy nhất trong phân khúc',
    ],
    standardPackage: [
      '01 Thân máy Leica NA730 Plus',
      '01 Hộp đựng chống sốc có khóa',
      '01 Quả dọi kim loại chuẩn',
      '01 Bộ dụng cụ hiệu chỉnh bọt thủy',
      '01 Tem kiểm định chất lượng Quatest 1',
    ],
    specs: {
      categoryType: 'OPTICAL_LEVEL',
      magnification: '30x',
      stdDevPerKm: '0.7 mm/km',
      ingressProtection: 'IP57 (Chống ngâm nước)',
      weightKg: 1.7,
      extraDetails: {
        'Đường kính vật kính': '40 mm',
        'Khoảng cách ngắm ngắn nhất': '0.7 m',
        'Phạm vi bù trừ tự động': '± 15\'',
      },
    },
  },
  {
    id: 'prod-sokkia-b40a',
    slug: 'may-thuy-binh-tu-dong-sokkia-b40a',
    sku: 'LV-SOKKIA-B40A',
    name: 'Máy Thủy Bình Sokkia B40A (24x - Sai Số 1.5mm/km)',
    brand: BRANDS[3],
    category: CATEGORIES[2],
    basePrice: 6200000,
    salePrice: 5400000,
    stock: 35,
    condition: 'NEW_100',
    origin: 'Nhật Bản',
    warrantyMonths: 24,
    isQuoteOnly: false,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 68,
    mainImage: 'https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: 'Chiếc máy thủy bình quốc dân tại Việt Nam với con lắc giảm chấn từ tính chống rung động mạnh từ xe lu và máy ủi.',
    fullDesc: 'Sokkia B40A nổi tiếng với độ bền vô địch trên các công trường san lấp và giao thông. Hệ thống giảm chấn từ tính giúp con lắc tự cân bằng tức thì ngay cả khi có chấn động lớn từ các phương tiện cơ giới hạng nặng hoạt động gần chân máy.',
    highlights: [
      'Độ phóng đại 24x, sai số 1.5mm trên 1km đo lặp',
      'Bộ giảm chấn từ tính độc quyền Sokkia triệt tiêu rung chấn',
      'Tiêu chuẩn chống nước IPX6 chịu được tia nước áp lực cao',
      'Tặng kèm Chân nhôm máy thủy bình + Mia nhôm 5m rút số đen đỏ',
    ],
    standardPackage: [
      '01 Máy thủy bình Sokkia B40A',
      '01 Chân máy hợp kim nhôm',
      '01 Mia nhôm 5m rút kèm bọt thủy mia',
      '01 Hộp đựng máy',
      '01 Giấy kiểm định hiệu chuẩn 12 tháng',
    ],
    specs: {
      categoryType: 'OPTICAL_LEVEL',
      magnification: '24x',
      stdDevPerKm: '1.5 mm/km',
      ingressProtection: 'IPX6',
      weightKg: 1.7,
    },
  },
  {
    id: 'prod-acc-leica-gpr111',
    slug: 'bo-guong-don-leica-gpr111-chinh-hang',
    sku: 'ACC-LEICA-GPR111',
    name: 'Bộ Gương Đơn Leica GPR111 (Hằng Số 0mm - Kèm Khung & Bảng Ngắm)',
    brand: BRANDS[0],
    category: CATEGORIES[4],
    basePrice: 2850000,
    stock: 25,
    condition: 'NEW_100',
    origin: 'Thụy Sĩ',
    warrantyMonths: 12,
    isQuoteOnly: false,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 15,
    mainImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: 'Gương chuẩn quang học Thụy Sĩ, hằng số gương 0mm, độ lệch tâm < 1mm, màng phản xạ chống trầy xước.',
    fullDesc: 'Gương đơn Leica GPR111 là phụ kiện tiêu chuẩn cho tất cả các dòng máy toàn đạc Leica. Bảng ngắm màu đỏ phản quang giúp người đứng máy dễ dàng bắt tiêu điểm từ cự ly hàng nghìn mét.',
    highlights: [
      'Hằng số gương: 0 mm',
      'Độ chính xác căn tâm: < 1.0 mm',
      'Tầm đo gương xa tới 2500m - 3500m với máy toàn đạc',
    ],
    standardPackage: [
      '01 Quả gương tròn Leica',
      '01 Khung đỡ hợp kim + Bảng ngắm đỏ',
      '01 Túi mềm bảo vệ có quai đeo',
    ],
    specs: {
      categoryType: 'ACCESSORY',
      extraDetails: {
        'Hằng số gương': '0 mm',
        'Độ lệch tâm': '< 1.0 mm',
        'Chất liệu': 'Thủy tinh quang học K9 cao cấp',
      },
    },
  },
  {
    id: 'prod-acc-carbon-pole',
    slug: 'sao-guong-carbon-rtk-2m6-khoa-van',
    sku: 'ACC-POLE-CARBON26',
    name: 'Sào Gương Sợi Carbon RTK 2.6m (Khóa Vặn Hợp Kim - Ren 5/8")',
    brand: BRANDS[4],
    category: CATEGORIES[4],
    basePrice: 1450000,
    stock: 40,
    condition: 'NEW_100',
    origin: 'Đài Loan',
    warrantyMonths: 12,
    isQuoteOnly: false,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 31,
    mainImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: 'Vật liệu 100% Carbon fiber chống giãn nở nhiệt độ môi trường, có bọt thủy tròn 20\' và vạch chia khắc laser.',
    fullDesc: 'Sào đo chuyên dụng cho máy GNSS RTK và máy toàn đạc điện tử. Sợi carbon nhẹ hơn nhôm 40% nhưng chịu lực uốn cực tốt, không bị giãn nở chiều dài dưới trời nắng gắt, đảm bảo cao độ Z luôn chuẩn xác.',
    highlights: [
      'Chiều dài tối đa 2.6m (thu gọn 1.35m)',
      '100% sợi Carbon cao cấp siêu nhẹ chỉ 1.1kg',
      'Khóa vặn hợp kim nhôm cứng cáp không bị trượt khóa',
      'Đầu ren tiêu chuẩn 5/8" phù hợp mọi loại ăng-ten RTK và gương phản xạ',
    ],
    standardPackage: [
      '01 Sào sợi Carbon 2.6m',
      '01 Mũi sào thép không gỉ thay thế được',
      '01 Túi bạt dù chống thấm có quai đeo vai',
    ],
    specs: {
      categoryType: 'ACCESSORY',
      extraDetails: {
        'Chiều dài kéo tối đa': '2.6 m',
        'Vật liệu': 'Carbon Fiber 100%',
        'Trọng lượng': '1.1 kg',
      },
    },
  },
  {
    id: 'prod-acc-tripod-gst120',
    slug: 'chan-may-hop-kim-nhom-nang-leica-gst120-9',
    sku: 'ACC-TRIPOD-GST120',
    name: 'Chân Máy Hợp Kim Nhôm Nặng Leica GST120-9 (Chống Xoắn Cho Toàn Đạc & RTK)',
    brand: BRANDS[0],
    category: CATEGORIES[4],
    basePrice: 3200000,
    stock: 18,
    condition: 'NEW_100',
    origin: 'Thụy Sĩ',
    warrantyMonths: 12,
    isQuoteOnly: false,
    isFeatured: false,
    rating: 5.0,
    reviewCount: 19,
    mainImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    shortDesc: 'Chân máy trắc địa hạng nặng đạt tiêu chuẩn ổn định chống xoắn ISO 12858-2, chịu tải 15kg cho toàn đạc 1".',
    fullDesc: 'Chân máy Leica GST120-9 được thiết kế đặc biệt cho các công việc đo góc chính xác cao (1" - 2"). Các khớp nối và khóa chốt được đúc bằng hợp kim đặc biệt đảm bảo không có độ rơ hay biến dạng xoắn ngay cả khi có gió giật mạnh trên công trường.',
    highlights: [
      'Tiêu chuẩn ổn định xoắn quốc tế ISO 12858-2-G',
      'Chân đế có bàn đạp chống trượt cắm sâu vào nền đất',
      'Khóa kẹp chân tác động nhanh kết hợp ốc siết phụ',
    ],
    standardPackage: [
      '01 Chân máy Leica GST120-9',
      '01 Dây đai khóa chân bảo quản',
      '01 Quai đeo vai tiện lợi',
    ],
    specs: {
      categoryType: 'ACCESSORY',
      extraDetails: {
        'Chiều cao làm việc': '110 cm đến 180 cm',
        'Trọng lượng': '6.4 kg',
        'Tải trọng tối đa': '15 kg',
      },
    },
  },
];
